### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Jinnrry** [Weipengzhou/yxb#1]
我想请问下，我现在也在写藏宝阁的爬虫，但是我是抓角色数据，用python抓的时候有个重定向一直过不去，提示浏览器不支持从http跳转到https您有这问题吗？现在用chrome+selenium在抓，但是性能实在是低，而且抓到的数据里面发现差不多有1/3是假数据

**Comment by Jinnrry** [comment]
看完你的代码，我瞬间顿悟，我靠，他网站是ajax请求数据的，不是后端渲染的，我自己想多了，另外问下，`(["AchPointTotal":1061,"iSmithski":1,"iMaxExpt1":20,"iHp_Max":2213,"outdoor_level":0,"ori_race":1,"addPoint":6,"more_attr":(["attrs":({(["lv":12,"idx":1,]),(["lv":0,"idx":10,]),(["lv":0,"idx":11,]),(["lv":0,"idx":2,]),(["lv":0,"idx":12,]),(["lv":0,"idx":8,]),(["lv":0,"idx":9,]),(["lv":18,"idx":6,]),(["lv":0,"idx":5,]),(["lv":0,"idx":7,]),(["lv":0,"idx":4,]),(["lv":0,"idx":3,]),(["lv":338,"idx":13,]),(["lv":491,"idx":14,]),}),]),"rent":0,"propKept":([]),"ExpJw":0,"rent_level":0,"shenqi_yellow":"","AllEquip":([189:(["cDesc":"等级 60#r封印命中等级 +12#r耐久度 426#r精炼等级 1#r#G法术防御 +18 #cEE82EE[+8]#r#G防御 +15 #cEE82EE[+8]#r#W制造者：一转眼八年梦强化打造#","iType":27201,]),1:(["cDesc":"#r等级 60 #r防御 +26 魔法 +60#r耐久度 160#r锻炼等级 6 镶嵌宝石 红玛瑙#r#G#G命中 +150#Y#Y#r#c4DBAF4特技：#c4DBAF4破血狂攻#Y#Y#r#G开运孔数：2孔/2孔#G#r符石: 力量 +1#n#G#r符石: 力量 +1 防御 +3#n#r#cEE82EE符石组合: 万里横行#r门派条件：无#r部位条件：无#r提升自身4点伤害#Y ","iType":2507,]),3:(["cDesc":"#r等级 60 #r防御 +33 敏捷 +27#r耐久度 179#r锻炼等级 4 镶嵌宝石 黑宝石#r#G#G速度 +32#Y#Y#r#c4DBAF4特技：#c4DBAF4命归术#Y#Y#r#G开运孔数：2孔/2孔#b#G#r符石: 命中 +4#n#b#G#r符石: 伤害 +1.5#n#r#cEE82EE符石组合: 无心插柳#r门派条件：无#r部位条件：无#r普通物理攻击时会造成溅射效果，对另外两个目标造成所受伤害15%的伤害，仅对NPC使用时有效。#Y ","iType":2707,]),188:(["cDesc":"等级 60#r法术防御 +12#r耐久度 528#r精炼等级 1#r#G速度 +7 #cEE82EE[+3]#r#G伤害 +6 #cEE82EE[+4]#r#W制造者：″海燕︷◆强化打造#","iType":27101,]),187:(["cDesc":"等级 60#r防御 +12#r耐久度 408#r精炼等级 3#r#G物理暴击等级 +6 #cEE82EE[+12]#r#G伤害 +6 #cEE82EE[+12]#r#W制造者：好莱坞影帝强化打造#","iType":27001,]),5:(["cDesc":"#r等级 60 五行 土#r#r防御 +35 气血 +403#r耐久度 56#r锻炼等级 6 镶嵌宝石 光芒石#Y#r#G开运孔数：2孔/2孔#b#G#r符石: 力量 +1#n#G#r符石: 力量 +1 防御 +3#n#r#cEE82EE符石组合: 万里横行#r门派条件：无#r部位条件：无#r提升自身4点伤害#Y#r#W制造者：＂糖果ｙｏ！#Y#r#Y熔炼效果：#r#Y#r+8气血#Y ","iType":2911,]),4:(["cDesc":"#r等级 60 #r灵力 +125#r耐久度 147#r锻炼等级 5 镶嵌宝石 舍利子#Y#r#G开运孔数：1孔/2孔#Y #r#W制造者：′风拂柳生#Y#r#Y熔炼效果：#r#Y#r+1灵力#Y ","iType":2810,]),6:(["cDesc":"#r等级 60 五行 金#r#r命中 +331 伤害 +249#r耐久度 237 修理失败 3次#r锻炼等级 5 镶嵌宝石 红玛瑙#r#G#G耐力 -4#Y #G力量 +18#Y#Y#r#G开运孔数：2孔/2孔#Y ","iType":1107,]),2:(["cDesc":"#r等级 60 五行 木#r#r防御 +165#r耐久度 337#r锻炼等级 5 镶嵌宝石 月亮石#r#G#G体质 +7 #G耐力 +13#Y#Y#r#G开运孔数：2孔/2孔#G#r符石: 伤害 +1.5#n#G#r符石: 命中 +4#n#r#cEE82EE符石组合: 无心插柳#r门派条件：无#r部位条件：无#r普通物理攻击时会造成溅射效果，对另外两个目标造成所受伤害15%的伤害，仅对NPC使用时有效。#Y#r#W制造者：桂林ね人ノ强化打造#Y#r#Y熔炼效果：#r#Y#r+1体质#Y ","iType":2607,]),]),"iOrgOffer":0,"total_horse":1,"iCGTotalAmount":10,"iExptSki1":9,"iMaxExpt3":20,"iSchOffer":119,"iDef_All":555,"iZhuanZhi":0,"iBeastSki4":0,"igoodness_sav":987,"AllSummon":({(["yuanxiao":0,"iHp":159,"growthMax":1236,"qianjinlu":0,"att_rate":0,"att":1224,"iJjFeedCd":0,"left_qlxl":7,"SPD_MAX":1550,"carrygradezz":0,"ATK_MAX":1550,"MS_MAX":1800,"lastchecksubzz":2018,"csavezz":"1224|1224|1150|1309|4256|3000","DEF_MAX":1550,"ruyidan":0,"mp":3000,"spe":1150,"life":6750,"all_skills":(["308":1,"428":1,]),"iStr_all":21,"grow":1212,"jj_extra_add":0,"sjg":0,"iGenius":0,"iMag_all":17,"iMp_max":61,"iDef_All":25,"def":1224,"MP_MAX":3050,"lianshou":0,"summon_equip4_type":0,"iType":102070,"HP_MAX":5500,"iRealColor":0,"iCor_all":22,"iMp":61,"tmp_lingxing":0,"summon_equip4_desc":"","iMagDef_all":28,"jinjie":(["core":([]),"cnt":0,"lx":0,]),"summon_color":0,"iBaobao":1,"core_close":0,"iAtt_F":4,"iAtt_all":25,"summon_core":([]),"iPoint":0,"iGrade":0,"iRes_all":16,"dod":1309,"hp":4256,"iSpe_all":24,"iDex_All":27,"iHp_max":159,"iDod_All":31,]),(["yuanxiao":0,"iHp":1668,"growthMax":1236,"qianjinlu":0,"att_rate":0,"att":1060,"iJjFeedCd":0,"left_qlxl":7,"SPD_MAX":1550,"carrygradezz":0,"ATK_MAX":1550,"MS_MAX":1800,"lastchecksubzz":2018,"csavezz":"1060|1440|1547|1320|3850|2100","DEF_MAX":1550,"ruyidan":0,"mp":2100,"spe":1547,"life":6201,"all_skills":(["306":1,"411":1,"429":1,]),"iStr_all":68,"grow":1176,"jj_extra_add":0,"sjg":0,"iGenius":0,"iMag_all":65,"iMp_max":418,"iDef_All":234,"def":1440,"MP_MAX":3050,"lianshou":0,"summon_equip4_type":0,"iType":102071,"HP_MAX":5500,"iRealColor":0,"iCor_all":212,"iMp":418,"tmp_lingxing":0,"summon_equip4_desc":"","iMagDef_all":196,"jinjie":(["core":([]),"cnt":0,"lx":0,]),"summon_color":0,"iBaobao":1,"core_close":0,"iAtt_F":2,"iAtt_all":241,"summon_core":([]),"iPoint":5,"iGrade":45,"iRes_all":57,"dod":1320,"hp":3850,"iSpe_all":143,"iDex_All":221,"iHp_max":1668,"iDod_All":188,]),}),"iExptSki3":0,"iNutsNum":50,"iUpExp":192465768,"iMp":406,"iBeastSki2":0,"iMaxExpt2":20,"iCash":77340,"pet":({}),"iPcktPage":0,"total_avatar":4,"iCGBoxAmount":1,"iDesc":0,"iSaving":0,"iRes_All":89,"iSumAmount":8,"iMarry2":0,"ori_desc":2002,"datang_feat":5522,"iTotalMagDam_all":563,"iMag_All":83,"iDod_All":338,"jiyuan":0,"bid":0,"iHp":2158,"sword_score":0,"commu_gid":0,"iMaxExpt4":20,"iExptSki4":9,"TA_iAllPoint":0,"changesch":({}),"commu_name":0,"iSchool":1,"sum_exp":11,"iDamage_All":1111,"iExptSki5":0,"iSewski":0,"shenqi_pos":({0,0,}),"ExpJwBase":1000000000,"iGoodness":423,"HugeHorse":([152:(["iSkill":0,"nosale":0,"iType":11140,"cName":"开明天兽","iSkillLevel":0,"order":1,]),]),"iTotalMagDef_all":529,"TA_iAllNewPoint":1,"iBeastSki3":0,"usernum":17835901,"all_skills":(["174":1,"202":20,"179":1,"197":1,"1":79,"170":1,"52016":1,"196":1,"204":19,"211":27,"52032":1,"2":79,"52031":1,"169":1,"237":2,"154":4,"8":79,"207":7,"160":1,"208":20,"201":82,"4":79,"173":1,"5":79,"230":8,"7":79,"212":38,"198":1,"210":1,"20802":1,"6":79,]),"iIcon":2,"normal_horse":1,"farm_level":0,"iBeastSki1":2,"iHp_Eff":2213,"iMp_Max":466,"HeroScore":0,"iExptSki2":9,"ExAvt":([1:(["iType":14401,"order":1,"cName":"动物装饰篮",]),3:(["iType":14811,"order":3,"cName":"鬼脸南瓜",]),4:(["iType":20013,"order":4,"cName":"怀旧剑侠客炫卡",]),2:(["iType":14585,"order":2,"cName":"云雾足迹",]),]),"iErrantry":0,"cOrg":"","iStr_All":470,"iLearnCash":318669,"iSumAmountEx":0,"fabao":([1:(["cDesc":"0#Y灵气：#G200#Y 五行：#G水#Y#r修炼境界：第#G2#Y层 #c2189DE驾轻就熟#Y","iType":6068,]),13:(["cDesc":"0#Y灵气：#G50 #Y 五行：#G水#Y#r修炼境界：第#G0#Y层 #c7D7E82初具法力#Y","iType":6006,]),3:(["cDesc":"0#Y灵气：#G144#Y 五行：#G木#Y#r修炼境界：第#G7#Y层 #cFFCF2D神乎其技#Y","iType":6004,]),12:(["cDesc":"0#Y灵气：#G28 #Y 五行：#G火#Y#r修炼境界：第#G4#Y层 #c13E1EC出类拔萃#Y","iType":6002,]),23:(["cDesc":"0#Y灵气：#G200#Y 五行：#G金#Y#r修炼境界：第#G0#Y层 #c7D7E82初具法力#Y","iType":6068,]),2:(["cDesc":"0#Y灵气：#G0 #Y 五行：#G金#Y#r修炼境界：第#G5#Y层 #c01FEC5腾云驾雾#Y","iType":6056,]),]),"iBadness":0,"AllRider":([2:(["mattrib":"力量","all_skills":([]),"ExtraGrow":0,"exgrow":12647,"iType":505,"iGrade":85,]),]),"cName":"小孩丶游神","icolor_ex":0,"iPoint":0,"iGrade":69,"energy":1,"iCGBodyAmount":10,"iSpe_All":108,"iPride":800,"iRace":1,"iAtt_All":1600,"i3FlyLv":0,"shenqi":([]),"idbid_desc":({}),"xianyu":81,"iDex_All":188,"iCor_All":117,"iSkiPoint":1,"iMagDef_All":491,"iMarry":0,])` 他这种是什么数据格式啊，我看着像json，但是又不是json，我查了好久都没找到这个是什么数据格式

**Comment by Weipengzhou** [comment]
你看藏宝阁的几个js文件就知道了，js里有过滤无效数据的方法。
